### ISSUE TITLE
NavBar, <div> in <div> error

### ISSUE THREAD

**Issue by EvenAsl** [realfagskjelleren/realfagskjelleren.no#1]
https://github.com/realfagskjelleren/realfagskjelleren.no/blob/06a09d542a686487c8731412d64cce6db18921ea/client/src/components/NavBar.tsx#L33-L50

## Error from browser console when user is logged in:
Did not expect server HTML to contain a `<div>` in `<div>`.

## Expected behavior:
No browser error.

## Possible solution:
It seems to be a hydration issue, and rewriting the entire NavBar component by using useEffect from React should solve it.

EDIT: Realized there was a useless button in the NavBar, so updated reference to code.

**Comment by MartinSkatvedt** [comment]
Should be solved with #10
